swagger: "2.0"
info:
  description: "Books API documented using swagger"
  version: "0.0.1"
  title: "Books API"
  license:
    name: "MIT"
host: "localhost:3000"
basePath: "/books/"
paths:
  /list:
    get:
      summary: "List all books" 
      description: ""
      responses:
        200:
          description: "JSON array of all books"
          schema:
            type: array
            items:
              $ref: "#/definitions/Book"
  /insert:
    post:
      summary: "Insert a book" 
      description: ""
      parameters:
      - in: "body"
        name: "book"
        schema:
          $ref: "#/definitions/Book"
      responses:
        200:
          description: "OK"
  /get:
    get:
      summary: "Get book by id" 
      description: ""
      parameters:
      - in: "query"
        name: "id"
        type: "integer"
      responses:
        200:
          description: "A book with specified id"
          schema:
            $ref: "#/definitions/Book"
        404:
          description: "Not found"
  /delete:
    delete:
      summary: "Delete a book" 
      description: ""
      parameters:
      - in: "query"
        name: "id"
        type: "integer"
      responses:
        200:
          description: "OK"
        404:
          description: "Not found"
    
definitions:
  Book:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
          type: "string"
      author:
          type: "string"